root_path: 'D:\ID\Course\MYENV\HW1_MLOps\ml_project\'
data_path_for_modeling: 'data_for_modeling\data\heart_cleveland_upload.csv'
data_path_cat_features: data_for_modeling\features\model_lr\cat_features.csv
data_path_num_features: data_for_modeling\features\model_lr\num_features.csv
data_path_target_path: data_for_modeling\features\model_lr\target.csv
data_path_ohe_pkl: models_pkl\model_lr\ohe.pkl
data_path_scaler_pkl: models_pkl\model_lr\scaler.pkl
logging_path: logs\logging_model_lr.log
cat_features:
  - sex
  - cp
  - fbs
  - restecg
  - exang
  - slope
  - ca
  - thal
num_features:
  - age
  - trestbps
  - chol
  - thalach
  - oldpeak
target: condition

