root_path: 'D:\ID\Course\MYENV\HW1_MLOps\ml_project\'
data_path_for_prediction: 'data_for_prediction\data\data_sample.csv'
target_prediction_path: 'data_for_prediction\prediction\prediction_lr.csv'
data_path_ohe_pkl: models_pkl\model_lr\ohe.pkl
data_path_scaler_pkl: models_pkl\model_lr\scaler.pkl
data_path_model_pkl: models_pkl\model_lr\log_reg.pkl
logging_path: logs\logging_model_lr.log
cat_features:
  - sex
  - cp
  - fbs
  - restecg
  - exang
  - slope
  - ca
  - thal
num_features:
  - age
  - trestbps
  - chol
  - thalach
  - oldpeak
target: condition