apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replica
  labels:
    app: online-inference
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: online-inference
  template:
    metadata:
      name: online-inference-replica
      labels:
        app: online-inference
    spec:
      containers:
        - image: idlatypov/online-inference:v1
          name: online-inference
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"

