apiVersion: v1
kind: Pod
metadata:
  name: online-inference-probes
  labels:
    app: online-inference
spec:
  containers:
    - image: idlatypov/online-inference:v2
      name: online-inference
      imagePullPolicy: Always
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      readinessProbe:
        httpGet:
          path: /ready
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
      livenessProbe:
        httpGet:
          path: /live
          port: 8000
        initialDelaySeconds: 30
        periodSeconds: 5
