apiVersion: v1
kind: Pod
metadata:
  name: online-inference-res
  labels:
    app: online-inference
spec:
  containers:
    - image: docker-tutorial 
      name: online-inference
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "128Mi"
          cpu: "250m"
        limits:
          memory: "256Mi"
          cpu: "500m"

