root_path: 'D:\ID\Course\MYENV\HW1_MLOps\ml_project\'
data_path_cat_features: data_for_modeling\features\model_kn\cat_features.csv
data_path_num_features: data_for_modeling\features\model_kn\num_features.csv
data_path_target_path: data_for_modeling\features\model_kn\target.csv
data_path_model_pkl: models_pkl\model_kn\kn_clf.pkl
logging_path: logs\logging_model_kn.log
target: condition
test_size: 0.3
model_name: KNeighborsClassifier
model_param_name: n_neighbors
model_param_value: 23
seed: 0